apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: rajpimparkar/static-web-app
        ports:
        - containerPort: 80
